#library("lubridate")
library("dplyr")
data <- read.csv("household_power_consumption.txt",sep=";",na.strings = "?")
data <- tbl_df(data)
data <- mutate(data,datetime = paste(Date,Time))
data$Date <- dmy(data$Date)
data <- data[which(month(data$Date)==2 & year(data$Date)==2007 & (day(data$Date)==1 |day(data$Date)==2)),]
data$Time <- hms(data$Time)
data$datetime <- dmy_hms(data$datetime)
png(filename = "plot4.png",width = 480, height = 480, units = "px",bg = "white")
par(mfrow=c(2,2))
with(data,{
  plot(datetime,Global_active_power, type="l",ylab="Global Active Power (kilowatts)",xlab="")
  plot(datetime,Voltage, type="l",ylab="Voltage",xlab="datetime")
  plot(datetime,Sub_metering_1, type="l",col="black",ylab="Energy sub metering",xlab="")
  legend("topright", lwd=1, col = c("black","blue","red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty="n")  
  lines(datetime,Sub_metering_2,col="red")
  lines(datetime,Sub_metering_3,col="blue")
  plot(datetime,Global_reactive_power, type="l",ylab="Global_reactive_power",xlab="datetime")
  })
dev.off()
