library("lubridate")
library("dplyr")
data <- read.csv("household_power_consumption.txt",sep=";",na.strings = "?")
data <- tbl_df(data)
data <- mutate(data,datetime = paste(Date,Time))
data$Date <- dmy(data$Date)
data <- data[which(month(data$Date)==2 & year(data$Date)==2007 & (day(data$Date)==1 |day(data$Date)==2)),]
data$Time <- hms(data$Time)
data$datetime <- dmy_hms(data$datetime)
png(filename = "plot2.png",width = 480, height = 480, units = "px",bg = "white")
plot(data$datetime,data$Global_active_power, type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()
